### ISSUE TITLE
主題名稱重複的Post內容不會被下載

### ISSUE THREAD

**Issue by cm3d-legacy** [Amarillys/FanboxBatchDownloader#1]
希望能檔案命名規則可以改為post number，或單純使用原檔案名稱

**Comment by Amarillys** [comment]
請問是否可以提供一個符合此種情況的作者ID方便我進行測試呢

**Comment by Amarillys** [comment]
修改了，更新下試試看
- > [V0.22](https://github.com/Amarillys/FanboxBatchDownloader/commit/aee78611312dddb04f6e8728104358c81fb49956)
