### ISSUE TITLE
[Bug] Unzippable zip file generated when title has forbidden characters in filesystem

### ISSUE THREAD

**Issue by Msopopop** [Amarillys/FanboxBatchDownloader#2]
Version: beta_1.14.514.1919.8.10.80
Description:
When fanbox post's title have forbidden characters in filesystem (such as ? * : " < > \ / |), the downloader will generate zip successfully however this zip file will can not be unzipped (unless user edit the zip file to remove these chars) .
In Windows 11 Enterprise (22000.258), system alert me "This is not a vaild zip.".
Example: https://momota.fanbox.cc/posts/222922 --> "extra stage"
-----------------------------------------------------------  ^ --------- ^
-----------------------------------------------------------error------ error
I suggest to check and remove or replace(maybe to full-width characters) all the forbidden characters in order to generate correct and unzippable zip file.

**Comment by Msopopop** [comment]
By the way, using unzip command under Linux system can successfully unzip the zip file because unzip replaces all these forbidden characters to "_".

**Comment by Amarillys** [comment]
OK，I will try to do that.

**Comment by Amarillys** [comment]
I have published an commit to solve this issue.

Here is the link: https://github.com/Amarillys/FanboxBatchDownloader/commit/9d7b20dc268b230ca935234da84b23b3b0f9386f

Please update the script manually on TamperMonkey.
If it solves, reply to me here and I will update it on TamperMonkey.

**Comment by Msopopop** [comment]
It still seems that there are some problems.
problems occured at these posts:
https://momota.fanbox.cc/posts/1595834
https://momota.fanbox.cc/posts/1595801
here is the zip file for your debug: [モモタ_momota@64-65-0.zip](https://github.com/Amarillys/FanboxBatchDownloader/files/7576170/_momota%4064-65-0.zip)
![图片](https://user-images.githubusercontent.com/29355936/142760400-85a202c2-d513-4fe5-ae7e-c74c4f183e20.png)

**Comment by Amarillys** [comment]
There is no special char in filename, so I don't know why it occurred.
You can try other decompress tools.

**Comment by Msopopop** [comment]
Got that. Thanks for your reply.
