### ISSUE TITLE
[Feature request] Download not only image files in the post

### ISSUE THREAD

**Issue by Msopopop** [Amarillys/FanboxBatchDownloader#3]
Many creators will insert some non-image files such as .psd, .pdf, .ai files in there posts as attachments (also as rewards). It seemed that downloader is unable to handle these non-image files and choose not to download them. Is there any possibility to also download these attchments automatically?

**Comment by Amarillys** [comment]
PDF can be download.
You can take a test here: https://chiyo.fanbox.cc/

**Comment by Msopopop** [comment]
Thanks for reply. I will try that later.
